
DROP TABLE IF EXISTS TREATMENTS;

CREATE TABLE TREATMENTS(
id SERIAL PRIMARY KEY,
diseaseID INT NOT NULL,
treatmentID INT NOT NULL,,
FOREIGN KEY (diseaseID) REFERENCES DISEASES(id),
FOREIGN KEY (treatmentID) REFERENCES TREATMENTS(id)
);
