
DROP TABLE IF EXISTS TREATMENTS;

CREATE TABLE TREATMENTS(
id SERIAL PRIMARY KEY,
diseaseID INT NOT NULL,
therapyID INT NOT NULL,
duration varchar,
FOREIGN KEY (diseaseID) REFERENCES DISEASES(id),
FOREIGN KEY (therapyID) REFERENCES THERAPIES(id)
);
