
DROP TABLE IF EXISTS DIAGNOSIS;

CREATE TABLE DIAGNOSIS(
id SERIAL PRIMARY KEY,
disease_id INT NOT NULL,
diagnostic_test_id INT NOT NULL,
FOREIGN KEY (disease_id) REFERENCES DISEASES(id),
FOREIGN KEY (diagnostic_test_id) REFERENCES DIAGNOSTIC_TESTS(id)
);