
DROP TABLE IF EXISTS MANIFESTATIONS;

CREATE TABLE MANIFESTATIONS(
id SERIAL PRIMARY KEY,
disease_id INT NOT NULL,
symptom_id INT NOT NULL,
severity VARCHAR,
FOREIGN KEY (disease_id) REFERENCES DISEASES(id),
FOREIGN KEY (symptom_id) REFERENCES SYMPTOMS(id)
);
