
DROP TABLE IF EXISTS MEDICATIONS;

CREATE TABLE MEDICATIONS(
id SERIAL PRIMARY KEY,
name VARCHAR NOT NULL,
dosage VARCHAR NOT NULL
);

DROP TABLE IF EXISTS THERAPIES;

CREATE TABLE THERAPIES(
id SERIAL PRIMARY KEY,
name VARCHAR NOT NULL

DROP TABLE IF EXISTS DISEASES;

CREATE TABLE DISEASES(
id SERIAL PRIMARY KEY,
name VARCHAR NOT NULL,
condition VARCHAR NOT NULL
);

DROP TABLE IF EXISTS SYMPTOMS;

CREATE TABLE SYMPTOMS(
id SERIAL PRIMARY KEY,
name VARCHAR NOT NULL
);

DROP TABLE IF EXISTS DIAGNOSTIC_TESTS;

CREATE TABLE DIAGNOSTIC_TESTS(
id SERIAL PRIMARY KEY,
name VARCHAR NOT NULL,
labValue NUMERIC NOT NULL
);

DROP TABLE IF EXISTS BIOLOGICAL_STRUCTURES;

CREATE TABLE BIOLOGICAL_STRUCTURES(
id SERIAL PRIMARY KEY,
name VARCHAR NOT NULL,
);

DROP TABLE IF EXISTS PRESCRIPTIONS;

CREATE TABLE PRESCRIPTIONS(
id SERIAL PRIMARY KEY,
medicationID INT NOT NULL,
therapyID INT NOT NULL,
FOREIGN KEY (medicationID) REFERENCES MEDICATIONS(id),
FOREIGN KEY (therapyID) REFERENCES THERAPIES(id)

DROP TABLE IF EXISTS TREATMENTS;

CREATE TABLE TREATMENTS(
id SERIAL PRIMARY KEY,
diseaseID INT NOT NULL,
therapyID INT NOT NULL,
duration varchar,
FOREIGN KEY (diseaseID) REFERENCES DISEASES(id),
FOREIGN KEY (therapyID) REFERENCES THERAPIES(id)
);

DROP TABLE IF EXISTS MANIFESTATIONS;

CREATE TABLE MANIFESTATIONS(
id SERIAL PRIMARY KEY,
diseaseID INT NOT NULL,
symptomID INT NOT NULL,
severity VARCHAR,
FOREIGN KEY (diseaseID) REFERENCES DISEASES(id),
FOREIGN KEY (symptomID) REFERENCES SYMPTOMS(id)
);

DROP TABLE IF EXISTS DIAGNOSIS;

CREATE TABLE DIAGNOSIS(
id SERIAL PRIMARY KEY,
diseaseID INT NOT NULL,
diagnosticTestID INT NOT NULL,
FOREIGN KEY (diseaseID) REFERENCES DISEASES(id),
FOREIGN KEY (diagnosticTestID) REFERENCES DIAGNOSTIC_TESTS(id)
)
DROP TABLE IF EXISTS INVOLVEMENT;

CREATE TABLE INVOLVEMENTS(
id SERIAL PRIMARY KEY,
diseaseID INT NOT NULL,
biologicalStrID INT NOT NULL,
FOREIGN KEY (diseaseID) REFERENCES DISEASES(id),
FOREIGN KEY (biologicalStrID) REFERENCES BIOLOGICAL_STRUCTURES(id)
