
DROP TABLE IF EXISTS TREATMENTS;

CREATE TABLE TREATMENTS(
id SERIAL PRIMARY KEY,
disease_id INT NOT NULL,
treatment_id INT NOT NULL,
FOREIGN KEY (disease_ID) REFERENCES DISEASES(id),
FOREIGN KEY (treatment_ID) REFERENCES TREATMENTS(id)
);
