
DROP TABLE IF EXISTS MANIFESTATIONS;

CREATE TABLE MANIFESTATIONS(
id SERIAL PRIMARY KEY,
diseaseID INT NOT NULL,
symptomID INT NOT NULL,
severity VARCHAR,
FOREIGN KEY (diseaseID) REFERENCES DISEASES(id),
FOREIGN KEY (symptomID) REFERENCES SYMPTOMS(id)
);
