
DROP TABLE IF EXISTS PRESCRIPTIONS;

CREATE TABLE PRESCRIPTIONS(
id SERIAL PRIMARY KEY,
medicationID INT NOT NULL,
therapyID INT NOT NULL,
FOREIGN KEY (medicationID) REFERENCES MEDICATIONS(id),
FOREIGN KEY (therapyID) REFERENCES THERAPIES(id)
